GET https://apinodeadsupf-2lkh.onrender.com/alunos

###

POST https://apinodeadsupf-2lkh.onrender.com/alunos
Content-Type: application/json

{
    "name": "João 5",
    "email": "aajoa5o@upf.com",
    "age": 20
}

###

PUT http://localhost:3333/alunos/ac30d552-4625-459b-bea6-9bb269b80453
Content-Type: application/json

{
    "name": "João 3",
    "email": "ajoao@upf.com",
    "age": 220
}

###

DELETE  http://localhost:3333/alunos/ac30d552-4625-459b-bea6-9bb269b80453
